apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: evgenyvolovlikov/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.js'
                    dest: .
        - image: evgenyvolovlikov/comments
          context: comments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: evgenyvolovlikov/event-bus
          context: event-bus
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: evgenyvolovlikov/moderation
          context: moderation
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: evgenyvolovlikov/posts
          context: posts
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: evgenyvolovlikov/query
          context: query
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
